[project]
name = "spotifications"
version = "0.1.0"
description = "Spotify crawler to get latests releases of your favorite artists"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "spotipy>=2.25.1",
    "fastapi==0.117.1",
    "loguru==0.7.3",
]
