name: 🎧 Crawling latest artists releases

on:
  workflow_dispatch:
  schedule:
    - cron: '30 06 * * *'

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Set up virtualenv and install requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Crawl & notify about new updates
        run: |
          source .venv/bin/activate
          python src/crawler.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          TELEGRAM_BOT_TOKEN:  ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Save .last_crawling_date and .processed_releases_uris files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .last_crawling_date .processed_releases_uris
          git commit -m "[GHA] Update last crawling date" --allow-empty
          git push

      - name: Upload crawler logs
        uses: actions/upload-artifact@v4
        with:
          name: crawler_logs
          path: logs/
