name: 🎧 Crawling latest artists releases

on:
  workflow_dispatch:
  schedule:
    - cron: '36 15 * * *'

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install requirements with uv
        run: |
          python3.9 -m pip install uv
          uv pip install --system -r requirements.txt

      - name: Run Python script
        run: python src/main.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
