name: 💊 Linter

on: push
jobs:
  linter:
    env:
      FLAKE8_REPORT_FILE: flake8_report.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install flake8
        run:
          pip install flake8

      - name: Run linter
        run: |
          flake8 --config=setup.cfg --output-file=${{ env.FLAKE8_REPORT_FILE }}
          cat ${{ env.FLAKE8_REPORT_FILE }}

      - name: Upload flake8 report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flake8_report
          path: ${{ env.FLAKE8_REPORT_FILE }}
