name: 💊 Linter

on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Istall flake8
        run:
          pip install flake8

      - name: Run linter
        run:
          flake8 --config=setup.cfg
