name: 🆕 Updates playlist with chosen releases

on:
  workflow_dispatch:
  schedule:
    - cron: '36 15 * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache Python venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ runner.arch }}-

      - name: Create venv and install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3.9 -m pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Update playlist with saved releases
        run: |
          source .venv/bin/activate
          python src/playlist_updater.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          TELEGRAM_BOT_TOKEN:  ${{ secrets.TELEGRAM_BOT_TOKEN }}
