name: Update APT and Install Packages

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache APT
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ runner.arch }}

      - name: Update and Install Packages
        run: |
          sudo apt-get update && sudo apt-get install -y jq openssh-client gh make
