name: 🆕 Updates playlist with chosen releases

on:
  workflow_dispatch:
  schedule:
    : # At minute 30 past every 2nd hour from 4 through 20 by Kyiv/Europe
    - cron: '30 1-17/2 * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Set up virtualenv and install requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Update playlist with saved releases
        run: |
          source .venv/bin/activate
          python src/updater.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          TELEGRAM_BOT_TOKEN:  ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Upload updater logs
        uses: actions/upload-artifact@v4
        with:
          name: updater_logs
          path: logs/
